---
name: ðŸ“Š Build Performance

# Note! you can't safely use "pull_request_target" here
# This workflow is mostly useful for "internal PRs"
# External PRs won't be able to post a PR comment
#
# See https://github.com/preactjs/compressed-size-action/issues/54
# See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**

#jobs:
# Requires to update workflow due to yarn 3 syntax: renamed --frozen-lockfile into --immutable
# build-size:
#   name: ðŸ“Š Build Size Report
#   timeout-minutes: 30
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '16'
#         cache: yarn
#     - uses: preactjs/compressed-size-action@v2
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
#         build: ' && yarn build'
#         pattern: '{build/assets/js/main*js,build/assets/css/styles*css,.docusaurus/globalData.json,build/index.html,build/blog/index.html,build/blog/**/swiss-army-knife-for-zsh/*,build/docs/index.html,build/docs/getting_started/installation.html}'
#         strip-hash: '\.([^;]\w{7})\.'
#         minimum-change-threshold: 30
#         compression: none

jobs:
  build-time:
    name: ðŸ’¹ Build Time Perf
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - name: âœ¨ Installation
        run: yarn
      # Ensure build with a cold cache does not increase too much
      - name: Build (cold cache)
        run: yarn build --locale en
        timeout-minutes: 8
      # Ensure build with a warm cache does not increase too much
      - name: Build (warm cache)
        run: yarn build --locale en
        timeout-minutes: 2
