name: üåê Crowdin Action

on:
  push:
    branches: [ main ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: ‚§µÔ∏è Check out code from GitHub
      uses: actions/checkout@v2
      
    - name: üöÄ Run Crowdin action
      uses: crowdin/github-action@1.4.6
      with:
      # upload options
        upload_sources: true
        upload_translations: true
      # download options
        download_translations: true
        language: 'ja'
        push_translations: true
      # This is the name of the git branch that Crowdin will create when opening a pull request.
      # This branch does NOT need to be manually created. It will be created automatically by the action.
        localization_branch_name: l10n_crowdin_action
        create_pull_request: true
      env:
        GITHUB_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
