---
name: 'ğŸŒ Crowdin'

on:
  push:
    branches: [ main ]
    paths: 
      - 'i18n/**'
      - 'docs/**'
jobs:
  sync-rowdin:
    runs-on: ubuntu-latest
    steps:
    - name: 'â¤µï¸ Check out code from GitHub'
      uses: actions/checkout@v2
    - name: 'ğŸš€ Run Crowdin action'
      uses: crowdin/github-action@1.4.6
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        push_translations: true
        pull_request_labels: 'enhancement âœ¨, beginner-friendly ğŸ’•'
        create_pull_request: true
      env:
        GITHUB_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
